### ISSUE TITLE
I can't read my code because of the colors

### ISSUE THREAD

**Issue by tylergraf** [Galadirith/markdown-preview-plus#123]
Here's an example of my markdown with a code snippet.

`````` javascript
### Select Item
#### Select One Item
\```javascript
$scope.itemSelected = null;
$scope.$on('itemSelected', function(evt, item){
  if(item && item.label){
    $scope.itemSelected = item.label;
  }
});
\```
``````

(minus the leading /)

And here's the rendered markdown
![image](https://cloud.githubusercontent.com/assets/751054/10165836/74c591fe-667e-11e5-9210-8b9680de920f.png)

I can't read the code. It should look like this: :smile:

``` javascript
$scope.itemSelected = null;
$scope.$on('itemSelected', function(evt, item){
  if(item && item.label){
    $scope.itemSelected = item.label;
  }
});
```

**Comment by Galadirith** [comment]
Thanks @tylergraf. It looks like MPP is not meshing we'll with your theme. Could you please post the UI and Syntax themes that you were using when you took the screenshot along with any custom styles you'vew added, that would be really helpful then hopefully we can see what's going wrong.

I apologise in advance, I won't have a permanent internet connection until Friday so I'm unlikely to be able to fix this before then. Thanks again @tylergraf.

**Comment by tylergraf** [comment]
Thanks for the quick reply @Galadirith. Here is my syntax theme: https://github.com/ssteinker/atom-twilight and I'm just using Atom Dark as my UI theme.

I don't think I've added anything to my stylesheet:

```less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.tree-view {

}

.editor {
  font-family: Inconsolata, Monaco, Consolas, 'Courier New', Courier;
}

.editor .cursor {

}

```
