### ISSUE TITLE
[feature request] dark background

### ISSUE THREAD

**Issue by torsday** [Galadirith/markdown-preview-plus#178]
I would love a dark background, like the baked-in version of atom's markdown-preview.

**Comment by hanhua** [comment]
Me too

**Comment by liufuyang** [comment]
me too :pray:

**Comment by sitdisch** [comment]
You can get a dark background when you put that in your styles.less file
```less
.markdown-preview.markdown-preview {
  color: #CCC;
  background-color: #292929;
  // changes the writing color in the tables
  th,td {
   color: #292929;
  }
  // changes the writing color in the inline codes
  code {
  color: #292929;
  background-color: contrast(@syntax-background-color, lighten(@syntax-background-color, 8%), darken(@syntax-background-color, 6%));
  }
}
```
